"""Deterministic canonical fixture (spike #2 harness, Phase B step 1).

Mini versions of the bake-off datasets: 6 instruments (one delists mid-window),
60 business days of bars, quarterly fundamentals with publication lag,
a restatement storm, one split event, bitemporal universe membership.
Everything is generated by seeded integer arithmetic - no network, no randomness
at read time, so gold answers are stable forever.
"""
from __future__ import annotations

from datetime import date, timedelta

from .model import BitemporalRecord

SYMBOLS = ("AAA", "BBB", "CCC", "DDD", "EEE", "ZZZ")
START = date(2024, 1, 2)          # Tuesday
N_DAYS = 60
DELIST_EFFECTIVE = date(2024, 2, 20)   # ZZZ leaves the universe here
DELIST_KNOWN = date(2024, 2, 13)       # announce a week earlier
SPLIT_SYMBOL = "CCC"
SPLIT_VT = date(2024, 2, 15)
SPLIT_KNOWN = date(2024, 2, 1)


def business_days(start: date, n: int) -> list[str]:
    days, cur = [], start
    while len(days) < n:
        if cur.weekday() < 5:
            days.append(cur.isoformat())
        cur += timedelta(days=1)
    return days


def _lcg(seed: int) -> int:
    return (1103515245 * seed + 12345) % (2 ** 31)


def _price(sym: str, day_index: int) -> float:
    base = sum(ord(c) for c in sym)
    r = _lcg(base * 1000 + day_index) % 1000
    return round(50.0 + (base % 20) + day_index * 0.05 + r / 200.0, 4)


def _volume(sym: str, day_index: int) -> int:
    base = sum(ord(c) for c in sym)
    return 100_000 + (_lcg(base * 7 + day_index) % 50_000)


def _add_months(d: date, months: int) -> date:
    m = d.month - 1 + months
    y = d.year + m // 12
    return date(y, m % 12 + 1, min(d.day, 28))


def generate() -> list[BitemporalRecord]:
    recs: list[BitemporalRecord] = []
    days = business_days(START, N_DAYS)

    # --- bars: kt == vt (EOD vendor availability) ------------------------------
    for si, sym in enumerate(SYMBOLS):
        for di, vt in enumerate(days):
            px = _price(sym, di)
            recs.append(BitemporalRecord(
                namespace="bar", instrument_id=sym, vt=vt, kt=vt,
                payload={"open": px - 0.1, "high": px + 0.25, "low": px - 0.3,
                         "close": px, "volume": _volume(sym, di)},
                source="fixture", revision=0,
            ))

    # --- fundamentals: quarterly, publication lag 45d, restatement storm --------
    quarter_ends = [date(2023, 9, 30), date(2023, 12, 31)]
    for si, sym in enumerate(SYMBOLS):
        for qi, pe in enumerate(quarter_ends):
            kt = _add_months(pe, 1) + timedelta(days=15)   # ~45-day lag
            rev0 = BitemporalRecord(
                namespace="fundamental", instrument_id=sym,
                vt=pe.isoformat(), kt=kt.isoformat(),
                payload={"revenue": 1_000 + 100 * si + 25 * qi, "period": "Q"},
                source="fixture", revision=0,
            )
            recs.append(rev0)
            # restatement storm: every 5th (symbol, quarter) gets revised late
            if (si * len(quarter_ends) + qi) % 5 == 0:
                restate_kt = _add_months(kt, 2)
                recs.append(BitemporalRecord(
                    namespace="fundamental", instrument_id=sym,
                    vt=pe.isoformat(), kt=restate_kt.isoformat(),
                    payload={"revenue": 1_100 + 100 * si + 25 * qi, "period": "Q"},
                    source="fixture-restatement", revision=1,
                ))

    # --- corporate action: CCC 2:1 split --------------------------------------
    recs.append(BitemporalRecord(
        namespace="corporate_action", instrument_id=SPLIT_SYMBOL,
        vt=SPLIT_VT.isoformat(), kt=SPLIT_KNOWN.isoformat(),
        payload={"kind": "split", "ratio": 2.0}, source="fixture", revision=0,
    ))

    # --- universe membership: everyone in; ZZZ delists -------------------------
    for sym in SYMBOLS:
        recs.append(BitemporalRecord(
            namespace="universe", instrument_id=sym, vt=days[0], kt=days[0],
            payload={"index": "FIXIDX", "in_universe": True}, source="fixture", revision=0,
        ))
    recs.append(BitemporalRecord(
        namespace="universe", instrument_id="ZZZ", vt=DELIST_EFFECTIVE.isoformat(),
        kt=DELIST_KNOWN.isoformat(),
        payload={"index": "FIXIDX", "in_universe": False, "reason": "delisted"},
        source="fixture", revision=1,
    ))
    return recs


FIXTURE_PIN = None  # filled by snapshot_pin at test time; fixture is code, not data
